### ISSUE TITLE
Can't use "definitions" together with main schema

### ISSUE THREAD

**Issue by paul-michalik** [tangram-js/json-schema-editor#22]
Given I add a "definitions" section with reusable schemas to the main schema
   Then the "definitions" are not rendered in the right panel 
   And the "definitions" are not saved and restored on load
   Unless I move the "definitions" section up using the context menu in the tree editor
   But then the main schema is not shown
   And the main schema is not saved and restored on load

**Comment by dmushkov** [comment]
Any news about fixing those bug?

**Comment by scottmmjackson** [comment]
This bug is still here. 2 years later.

```
vue.esm.js:1897 TypeError: Cannot read properties of undefined (reading '$ref')
    at Object.getValue (JsonSchemaEditor.vue:490:1)
    at a.retrieveValue (SelectMenuItem.vue?bd95:48:1)
    at ae (vue.esm.js:1863:1)
    at a.e.$emit (vue.esm.js:3897:1)
    at a.<anonymous> (ContextMenu.vue?3757:112:1)
    at Array.<anonymous> (vue.esm.js:1989:1)
    at ce (vue.esm.js:1915:1)
```

This is dumped to the console when this happens.
